name: Create Pull Request

on:
  push:
    branches:
      - feature/*

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref }}
          target_branch: development
          title: My pull request
          template: .github/PULL_REQUEST_TEMPLATE.md
          body: "**Automated pull request**"
          reviewer: juliolimoli
          assignee: juliolimoli
          label: enhancement
          milestone: My milestone
          draft: true
          old_string: "<!-- Add your description here -->"
          new_string: "** Automatic pull request**"
          get_diff: true
          allow_no_diff: false