name: Create Pull Request

on:
  push:
    branches:
      - feature/*

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        base: ${{github.ref}}
        branch: development
        title: "Feature Branch Pull Request"
        body: "This pull request is for the feature branch."
