name: Open Pull Request for Feature Branch

on:
  push:
    branches:
      - feature/*

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: '[Auto] New feature'
        base: development
        title: '[Auto] New feature'
        body: "This pull request is for the feature branch."
