name: Open Pull Request
on:
  push:
    branches:
      - feature/*
permissions:
  pull-requests: write
jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: development
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Automatically Open Pull Request
          body: |
            This is an automatically opened pull request triggered by a push to the main branch.
          labels: auto-open-pr