name: Open Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Determine branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        
      - name: Check branch name and open pull request
        if: startsWith(env.BRANCH_NAME, 'feature/')
        run: |
          echo "Branch name matches the pattern, opening a pull request"
          # Your logic to open a pull request goes here
          
      - name: Skip branch name and pull request
        if: !startsWith(env.BRANCH_NAME, 'feature/')
        run: echo "Branch name does not match the pattern, skipping pull request"
