name: Open Pull Request
on:
  push:
    branches:
      - '**'
permissions:
  pull-requests: write
jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine branch name
        id: branch
        run: echo "::set-output name=branch_name::${{ github.ref }}"

      - name: Create Pull Request
        if: startsWith(steps.branch.outputs.branch_name, 'feature/')
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch.outputs.branch_name }}
          base: development
          title: "Open Pull Request from feature to development"
          body: |
            This is an automatically opened pull request triggered by a push to the main branch.
          labels: auto-open-pr