name: Open Pull Request
on:
  push:
    branches:
      - feature/*
permissions:
  contents: write
jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: Cloud - Update available list
            title: Cloud - Update available list
            body: Cloud - Update available list
            base: development
            labels: automated-pr, Clouds & Regions