name: Open Pull Request feature --> development
on:
  push:
    branches: 
      - 'feature/**'
jobs:
  open_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Install dependencies or perform any necessary setup steps here

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          title: "Merge feature branch to development"
          body: |
            This pull request aims to merge the feature branch into the development branch.

            Please review and merge if approved.
          base: development
          draft: false
      