name: Open Pull Request development --> main
on:
  pull_request:
    types:
      - closed
    branches: 
      - 'development'
jobs:
  open_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: PR and branch validation
      if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development' }}
      run: |
        echo The PR was merged

    - name: Create Pull Request
      run: |
        git config --global user.name "juliolimoli"
        git config --global user.email "juliolimolisilva@gmail.com"
        git checkout main
        git merge --no-ff ${{ github.ref }}
        git push origin main

    - name: Open Pull Request
      if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development' }}
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        title: Merge development into main
        body: This pull request merges the development branch into the main branch.
    # Install dependencies or perform any necessary setup steps here

    #- name: Open Pull Request
    #  
    #  uses: peter-evans/create-pull-request@v3
    #  with:
    #    token: 
    #    branch: 'development'
    #    title: "Merge feature development to main"
    #    body: |
    #      This pull request aims to merge the development branch into the main branch after the merge.
    #      Please review and merge if approved.
    #    base: main
    #    draft: false
      