name: Open Pull Request
on:
  push:
    branches:
      - 'feature/**'
permissions: write-all
jobs:
  open-pull-request:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Use the branch name
        run: |
          echo "The branch name is $BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GHA }}
          branch: feature/gha_workflows
          base: development
          title: "Open Pull Request from feature to development"
          body: |
            This is an automatically opened pull request triggered by a push to the main branch.
          labels: auto-open-pr